// NSQF seed catalogue for RojiSetu (Day 3).
//
// Honesty header: role titles mirror publicly listed NSDC / Sector Skill
// Council job-role names. NSQF levels and minimum education entries are
// INDICATIVE for prototype matching (the `indicative` flag says so on every
// row); verify against current qualification packs before any production
// claim. District lists are demand examples, not census data.
//
// Used from Day 4-5 by the recommendation engine: deterministic eligibility
// floor first (education, mobility, district, preference), AI ranks with
// reasons afterwards.

export type SectorId =
  | "apparel"
  | "electronics"
  | "beauty"
  | "agriculture"
  | "construction"
  | "retail";

export type EduLevel =
  | "none"
  | "class-5"
  | "class-8"
  | "class-10"
  | "class-12"
  | "iti"
  | "diploma"
  | "graduate";

export type PhysicalDemand = "seated-light" | "standing-moderate" | "field-heavy";
export type PreferenceFit = "self" | "wage" | "either";

export interface NsqfRole {
  id: string;
  roleTitle: string;
  sector: SectorId;
  nsqfLevel: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  minEducation: EduLevel;
  physicalDemand: PhysicalDemand;
  /** True when the role can plausibly be done from/near home. */
  workFromHomeOk: boolean;
  preferenceFit: PreferenceFit;
  exampleDistricts: string[];
  /** Matching hint tokens for skills/interests raw text (grows over time). */
  keywords: string[];
  indicative: true;
}

// Ordinal map so "class-10" style canonical values compare numerically.
export const EDU_SCORE: Record<EduLevel, number> = {
  none: 0,
  "class-5": 5,
  "class-8": 8,
  "class-10": 10,
  "class-12": 12,
  iti: 13,
  diploma: 14,
  graduate: 16,
};

/**
 * Deterministic eligibility floor, education side. Candidate canonical
 * values come from chat-extract ("none", "class-8", "iti", ...).
 * Unknown canonicals are treated as "none" - floors, never ceilings.
 */
export function meetsEducation(
  candidateCanonical: string | null,
  min: EduLevel
): boolean {
  const canon = (candidateCanonical && candidateCanonical in EDU_SCORE
    ? candidateCanonical
    : "none") as EduLevel;
  return EDU_SCORE[canon] >= EDU_SCORE[min];
}

export const NSQF_ROLES: NsqfRole[] = [
  // ---------------------------------------------------------------- APPAREL
  {
    id: "sewing-machine-operator",
    roleTitle: "Sewing Machine Operator",
    sector: "apparel",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "either",
    exampleDistricts: ["Varanasi (UP)", "Tiruppur (TN)", "Howrah (WB)", "Gaya (BR)"],
    keywords: ["stitch", "sew", "tailor", "silai", "सिलाई", "कपड़ा", "tayaar"],
    indicative: true,
  },
  {
    id: "self-employed-tailor",
    roleTitle: "Self Employed Tailor",
    sector: "apparel",
    nsqfLevel: 4,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Lucknow (UP)", "Kalaburagi (KA)", "Nagpur (MH)", "Cuttack (OD)"],
    keywords: ["tailor", "boutique", "silai", "सिलाई", "बुटीक", "कपड़े सीना"],
    indicative: true,
  },
  {
    id: "hand-embroidery-worker",
    roleTitle: "Hand Embroidery Worker",
    sector: "apparel",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "seated-light",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Lucknow (UP)", "Kutch (GJ)", "Jodhpur (RJ)", "Patna (BR)"],
    keywords: ["embroidery", "कढ़ाई", "kadhaai", "zari", "chikankari"],
    indicative: true,
  },
  {
    id: "handloom-weaver",
    roleTitle: "Handloom Weaver",
    sector: "apparel",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Varanasi (UP)", "Sambalpur (OD)", "Kanchipuram (TN)", "Nalbari (AS)"],
    keywords: ["weaving", "बुनाई", "handloom", "हथकरघा", "saree"],
    indicative: true,
  },
  {
    id: "apparel-quality-checker",
    roleTitle: "Apparel Quality Checker",
    sector: "apparel",
    nsqfLevel: 3,
    minEducation: "class-10",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["Gurugram (HR)", "Tiruppur (TN)", "Bengaluru (KA)"],
    keywords: ["quality", "checking", "garment", "गुणवत्ता"],
    indicative: true,
  },
  {
    id: "ironing-pressman",
    roleTitle: "Ironing and Finishing Assistant (Pressman)",
    sector: "apparel",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["Delhi (NCR)", "Mumbai (MH)", "Patna (BR)"],
    keywords: ["ironing", "press", "इस्त्री", "finishing"],
    indicative: true,
  },
  {
    id: "crochet-lace-maker",
    roleTitle: "Crochet Lace Maker",
    sector: "apparel",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "seated-light",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Narsapur (AP)", "Kollam (KL)", "Darjeeling (WB)"],
    keywords: ["crochet", "lace", "बुनाई", "handwork"],
    indicative: true,
  },
  {
    id: "boutique-assistant",
    roleTitle: "Boutique Design Assistant",
    sector: "apparel",
    nsqfLevel: 4,
    minEducation: "class-12",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["Jaipur (RJ)", "Lucknow (UP)", "Indore (MP)"],
    keywords: ["boutique", "fashion", "design", "फैशन", "बुटीक"],
    indicative: true,
  },
  // ------------------------------------------------------------ ELECTRONICS
  {
    id: "solar-pv-installer",
    roleTitle: "Solar PV Installer (Suryamitra)",
    sector: "electronics",
    nsqfLevel: 4,
    minEducation: "class-10",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["Jodhpur (RJ)", "Varanasi (UP)", "Gaya (BR)", "Kalaburagi (KA)"],
    keywords: ["solar", "सौर", "panel", "पैनल", "electrician"],
    indicative: true,
  },
  {
    id: "solar-pv-helper",
    roleTitle: "Solar PV Installer Helper",
    sector: "electronics",
    nsqfLevel: 2,
    minEducation: "class-8",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["Jodhpur (RJ)", "Ranchi (JH)", "Raipur (CG)"],
    keywords: ["solar", "सौर", "helper", "सहायक"],
    indicative: true,
  },
  {
    id: "home-appliance-technician",
    roleTitle: "Field Technician - Home Appliances",
    sector: "electronics",
    nsqfLevel: 4,
    minEducation: "class-10",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["Patna (BR)", "Bhopal (MP)", "Guwahati (AS)"],
    keywords: ["repair", "रिपेयर", "technician", "मशीन", "service"],
    indicative: true,
  },
  {
    id: "mobile-repair-technician",
    roleTitle: "Mobile Phone Repair Technician",
    sector: "electronics",
    nsqfLevel: 4,
    minEducation: "class-8",
    physicalDemand: "seated-light",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["mobile", "मोबाइल", "phone", "repair", "रिपेयर"],
    indicative: true,
  },
  {
    id: "led-light-technician",
    roleTitle: "LED Light Repair Technician",
    sector: "electronics",
    nsqfLevel: 4,
    minEducation: "class-8",
    physicalDemand: "seated-light",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["Kanpur (UP)", "Asansol (WB)"],
    keywords: ["led", "light", "repair", "रिपेयर"],
    indicative: true,
  },
  {
    id: "cctv-installation-technician",
    roleTitle: "CCTV Installation Technician",
    sector: "electronics",
    nsqfLevel: 4,
    minEducation: "class-10",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["cctv", "camera", "कैमरा", "security"],
    indicative: true,
  },
  {
    id: "inverter-battery-repair",
    roleTitle: "Inverter and Battery Repair Assistant",
    sector: "electronics",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "seated-light",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["battery", "inverter", "बैटरी", "repair"],
    indicative: true,
  },
  {
    id: "domestic-wiring-helper",
    roleTitle: "Domestic Wiring Helper",
    sector: "electronics",
    nsqfLevel: 2,
    minEducation: "class-8",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["wiring", "बिजली", "electrician helper", "तार"],
    indicative: true,
  },
  // ---------------------------------------------------------------- BEAUTY
  {
    id: "assistant-beauty-therapist",
    roleTitle: "Assistant Beauty Therapist",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["beauty", "parlour", "ब्यूटी", "पार्लर", "makeup"],
    indicative: true,
  },
  {
    id: "beauty-therapist",
    roleTitle: "Beauty Therapist",
    sector: "beauty",
    nsqfLevel: 4,
    minEducation: "class-10",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["beauty", "parlour", "ब्यूटी", "facial", "skin"],
    indicative: true,
  },
  {
    id: "hairdresser-assistant",
    roleTitle: "Hairdresser Assistant",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["hair", "बाल", "salon", "सैलून"],
    indicative: true,
  },
  {
    id: "barber-assistant",
    roleTitle: "Barber - Men's Grooming Assistant",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["barber", "नाई", "haircut", "दाढ़ी", "सैलून"],
    indicative: true,
  },
  {
    id: "mehendi-artist",
    roleTitle: "Bridal Mehendi Artist",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "none",
    physicalDemand: "seated-light",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Jodhpur (RJ)", "Lucknow (UP)", "Hyderabad (TG)"],
    keywords: ["mehendi", "mehndi", "मेहंदी", "bridal"],
    indicative: true,
  },
  {
    id: "nail-art-assistant",
    roleTitle: "Nail Art Assistant",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "seated-light",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["state capitals"],
    keywords: ["nail", "नेल", "manicure"],
    indicative: true,
  },
  {
    id: "yoga-assistant-trainer",
    roleTitle: "Yoga Assistant Trainer",
    sector: "beauty",
    nsqfLevel: 4,
    minEducation: "class-10",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["yoga", "योग", "fitness", "प्राणायाम"],
    indicative: true,
  },
  {
    id: "spa-assistant",
    roleTitle: "Spa and Wellness Assistant",
    sector: "beauty",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["state capitals", "tourist towns"],
    keywords: ["spa", "wellness", "स्पा", "massage"],
    indicative: true,
  },
  // ------------------------------------------------------------ AGRICULTURE
  {
    id: "organic-grower",
    roleTitle: "Organic Grower",
    sector: "agriculture",
    nsqfLevel: 4,
    minEducation: "class-8",
    physicalDemand: "field-heavy",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Sikkim districts", "Kalaburagi (KA)", "Sagar (MP)"],
    keywords: ["organic", "जैविक", "farming", "खेती", "vegetables"],
    indicative: true,
  },
  {
    id: "vermicompost-producer",
    roleTitle: "Vermicompost Producer",
    sector: "agriculture",
    nsqfLevel: 3,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Gaya (BR)", "Raipur (CG)", "Barmer (RJ)"],
    keywords: ["vermicompost", "केंचुआ", "खाद", "compost"],
    indicative: true,
  },
  {
    id: "dairy-entrepreneur",
    roleTitle: "Dairy Farmer Entrepreneur",
    sector: "agriculture",
    nsqfLevel: 4,
    minEducation: "class-5",
    physicalDemand: "field-heavy",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Anand (GJ)", "Karnal (HR)", "Erode (TN)"],
    keywords: ["dairy", "गाय", "भैंस", "दूध", "milk"],
    indicative: true,
  },
  {
    id: "poultry-farm-worker",
    roleTitle: "Poultry Farm Worker",
    sector: "agriculture",
    nsqfLevel: 3,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "either",
    exampleDistricts: ["Namakkal (TN)", "Hyderabad hinterland (TG)", "Ranchi (JH)"],
    keywords: ["poultry", "मुर्गी", "अंडा", "chicken"],
    indicative: true,
  },
  {
    id: "goat-rearer",
    roleTitle: "Goat Rearer",
    sector: "agriculture",
    nsqfLevel: 3,
    minEducation: "none",
    physicalDemand: "field-heavy",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Gaya (BR)", "Barmer (RJ)", "Kalaburagi (KA)"],
    keywords: ["goat", "बकरी", "rearing", "पशु"],
    indicative: true,
  },
  {
    id: "beekeeper",
    roleTitle: "Beekeeper",
    sector: "agriculture",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "field-heavy",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Sundarbans (WB)", "Muzaffarpur (BR)", "Nilgiris (TN)"],
    keywords: ["bee", "मधुमक्खी", "शहद", "honey", "apiculture"],
    indicative: true,
  },
  {
    id: "mushroom-grower",
    roleTitle: "Mushroom Grower",
    sector: "agriculture",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["Solan (HP)", "Varanasi (UP)", "Coimbatore (TN)"],
    keywords: ["mushroom", "मशरूम", "कुकुरमुत्ता"],
    indicative: true,
  },
  {
    id: "nursery-worker",
    roleTitle: "Plant Nursery Worker",
    sector: "agriculture",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["nursery", "पौधशाला", "plants", "बीज"],
    indicative: true,
  },
  // ----------------------------------------------------------- CONSTRUCTION
  {
    id: "assistant-mason",
    roleTitle: "Assistant Mason",
    sector: "construction",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["mason", "राज", "मिस्त्री", "construction"],
    indicative: true,
  },
  {
    id: "bar-bender-helper",
    roleTitle: "Bar Bender and Fixer Helper",
    sector: "construction",
    nsqfLevel: 3,
    minEducation: "none",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["bar bending", "सरिया", "steel", "लोहा"],
    indicative: true,
  },
  {
    id: "painter-assistant",
    roleTitle: "Painter and Decorator Assistant",
    sector: "construction",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["painting", "पेंट", "रंग", "wall"],
    indicative: true,
  },
  {
    id: "plumber-assistant",
    roleTitle: "Plumber Assistant",
    sector: "construction",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["plumber", "प्लंबर", "pipe", "नल"],
    indicative: true,
  },
  {
    id: "tile-layer-helper",
    roleTitle: "Tile and Stone Layer Helper",
    sector: "construction",
    nsqfLevel: 3,
    minEducation: "class-5",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["tiles", "टाइल", "flooring", "फर्श"],
    indicative: true,
  },
  {
    id: "scaffolding-helper",
    roleTitle: "Scaffolding Assistant",
    sector: "construction",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["big cities"],
    keywords: ["scaffolding", "मचान", "height"],
    indicative: true,
  },
  {
    id: "waterproofing-assistant",
    roleTitle: "Waterproofing Assistant",
    sector: "construction",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["big cities"],
    keywords: ["waterproofing", "छत", "leakage"],
    indicative: true,
  },
  {
    id: "site-helper",
    roleTitle: "Construction Site Helper",
    sector: "construction",
    nsqfLevel: 1,
    minEducation: "none",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["helper", "मजदूरी", "site", "labour"],
    indicative: true,
  },
  // ---------------------------------------------------------------- RETAIL
  {
    id: "retail-sales-associate",
    roleTitle: "Retail Sales Associate",
    sector: "retail",
    nsqfLevel: 3,
    minEducation: "class-10",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["sales", "shop", "दुकान", "store", "सेल्स"],
    indicative: true,
  },
  {
    id: "retail-store-assistant",
    roleTitle: "Retail Store Assistant",
    sector: "retail",
    nsqfLevel: 2,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["shop", "दुकान", "counter", "store"],
    indicative: true,
  },
  {
    id: "warehouse-picker",
    roleTitle: "Warehouse Picker",
    sector: "retail",
    nsqfLevel: 3,
    minEducation: "class-8",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["Bhiwandi (MH)", "Farrukhnagar (HR)", "Hosur (TN)"],
    keywords: ["warehouse", "गोदाम", "packing", "stock"],
    indicative: true,
  },
  {
    id: "delivery-associate",
    roleTitle: "Delivery Associate",
    sector: "retail",
    nsqfLevel: 2,
    minEducation: "class-8",
    physicalDemand: "field-heavy",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every district HQ"],
    keywords: ["delivery", "डिलीवरी", "parcel", "courier"],
    indicative: true,
  },
  {
    id: "grading-sorting-worker",
    roleTitle: "Produce Grading and Sorting Worker",
    sector: "retail",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["Azadpur (DL)", "Vashi (MH)", "Koyambedu (TN)"],
    keywords: ["grading", "sorting", "छँटाई", "vegetables"],
    indicative: true,
  },
  {
    id: "domestic-data-entry",
    roleTitle: "Domestic Data Entry Operator",
    sector: "retail",
    nsqfLevel: 4,
    minEducation: "class-12",
    physicalDemand: "seated-light",
    workFromHomeOk: true,
    preferenceFit: "either",
    exampleDistricts: ["every district HQ"],
    keywords: ["computer", "कंप्यूटर", "typing", "data entry", "keyboard"],
    indicative: true,
  },
  {
    id: "pickle-papad-maker",
    roleTitle: "Pickle and Papad Maker (Home Micro-enterprise)",
    sector: "retail",
    nsqfLevel: 2,
    minEducation: "none",
    physicalDemand: "seated-light",
    workFromHomeOk: true,
    preferenceFit: "self",
    exampleDistricts: ["every district HQ"],
    keywords: ["pickle", "अचार", "papad", "पापड़", "food"],
    indicative: true,
  },
  {
    id: "kirana-counter-helper",
    roleTitle: "Kirana Counter Helper",
    sector: "retail",
    nsqfLevel: 1,
    minEducation: "none",
    physicalDemand: "standing-moderate",
    workFromHomeOk: false,
    preferenceFit: "wage",
    exampleDistricts: ["every market town"],
    keywords: ["kirana", "किराना", "shop", "दुकान"],
    indicative: true,
  },
];

export const SECTORS: SectorId[] = [
  "apparel",
  "electronics",
  "beauty",
  "agriculture",
  "construction",
  "retail",
];

export function rolesBySector(sector: SectorId): NsqfRole[] {
  return NSQF_ROLES.filter((r) => r.sector === sector);
}